spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/BookStore
          jwk-set-uri: http://localhost:8080/realms/BookStore/protocol/openid-connect/certs
  application:
    name: BookStore-API
  datasource:
    url: jdbc:mysql://localhost:3306/bookstore
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Gaetano24072001!
  jpa:
    hibernate:
      ddl-auto: validate # Questa opzione non determina cambiamenti del database, effettua solo una validazione
    properties:
      hibernate:
        #/show_sql: true # Mostra le query SQL generate da Hibernate (utile per scopi di debug)
        format_sql: true # Formatta le query SQL generate per una migliore leggibilità

server:
  port: 8081

jwt:
  auth:
    converter:
      principle-attribute: preferred_username